# 3.1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:

banana_prototype = np.array([-1, 1, -1]).reshape((3, 1))
pineapple_prototype = np.array([-1, -1, 1]).reshape((3, 1))
prototypes = np.array([banana_prototype.T[0], pineapple_prototype.T[0]])

near_pineapple = np.array([1, -1, 1]).reshape((3, 1))
near_banana = np.array([-1, 1, -1]).reshape((3, 1))

In [ ]:
print(prototypes)

[[-1  1 -1]
 [-1 -1  1]]


## 3.1.1. Decision Boundary

i.   Design a perceptron to recognize these patterns.

Note: Decision boundary is a weight that points towards that of a banana.

In [ ]:
banana_prototype = np.array([-1, 1, -1]).reshape((3, 1))
pineapple_prototype = np.array([-1, -1, 1]).reshape((3, 1))

# Weight matrix and bias determined by decision boundary.
decision_boundary = (banana_prototype != pineapple_prototype).astype(int).reshape((1, len(banana_prototype)))
print(decision_boundary)

[[0 1 1]]


## 3.1.2. Perceptron





### 3.2.1. Transfer functions

In [25]:
class transfer_functions():
  import numpy as np

  # Transfer functions as defined by Neural Network Toolbox for MATLAB

  def hardlim(n):
      """
      Hard Limit
      """
      if n < 0:
          return 0
      else:
          return 1

  def hardlims(n):
      """
      Symmetrical Hard Limit
      """
      if n < 0:
          return -1
      else:
          return 1

  def purelin(n):
      """
      Linear
      """
      return n

  def satlin(n):
      """
      Saturing Linear
      """
      if n < 0:
          return 0
      elif n > 1:
          return 1
      else:
          return n

  def satlins(n):
      """
      Symmetric Saturating Linear
      """
      if n < -1:
          return -1
      elif n > 1:
          return 1
      else:
          return n

  def logsig(n):
      """
      Log-Sigmoid
      """
      return 1/(1+np.exp(-1*n))

  def tansig(n):
      """
      Hyperbolic Tangent Sigmoid
      """
      return (np.exp(n) - np.exp(-1*n))/(np.exp(n) + np.exp(-1*n))

  def poslin(n):
      """
      Positive Linear
      """
      if n < 0:
          return 0
      else:
          return n

  def compet(n):
      """
      Competitive

      """
      return (n > 0).astype(np.int)




In [26]:
class Perceptron(object):
    def __init__(self, W, b, transfer_function=hardlims):
        self.Weights = W
        self.bias = b
        self.transfer_function = np.vectorize(transfer_function)

    def classify(self, prototype):
        net_input = self.Weights.dot(prototype) + self.bias
        return self.transfer_function(net_input)

NameError: ignored

### 3.2.2. Perceptron

In [ ]:
banana_prototype = np.array([-1, 1, -1]).reshape((3, 1))
pineapple_prototype = np.array([-1, -1, 1]).reshape((3, 1))

# Weight matrix and bias determined by decision boundary.
decision_boundary = (banana_prototype != pineapple_prototype).astype(int).reshape((1, len(banana_prototype)))
print(decision_boundary)
bias = 0

# Create a Perceptron instance
bp_perceptron = Perceptron(W=decision_boundary, b=0)

# Classify prototypes
print("Classification results:")
print("\tNear Pineapple:", bp_perceptron.classify(near_pineapple))
print("\tNear Banana:", bp_perceptron.classify(near_banana))

[[0 1 1]]


NameError: ignored

In [ ]:
bp_perceptron = Perceptron(W=decision_boundary, b=0)
print("\t", "near_pineapple", bp_perceptron.classify(near_pineapple))
print("\t", "near_banana", bp_perceptron.classify(near_banana))

## 3.1.3. Hamming network

### 3.3.1. Hamming nw

In [ ]:
class HammingNetwork(object):
    def __init__(self, prototypes):
        self.feedForwardLayer = self.FeedForwardLayer(W=prototypes)
        self.recurrentLayer = self.RecurrentLayer()

    def classify(self, obj):
        a1 = self.feedForwardLayer.propagate(obj=obj)
        recurrent_result = self.recurrentLayer.propagate(initial_a=a1)
        return compet(recurrent_result)

    class FeedForwardLayer(object):
        def __init__(self, W, transfer_function=purelin):
            self.Weights = W
            self.bias = np.repeat(self.Weights.shape[0], self.Weights.shape[0]).reshape((self.Weights.shape[0], 1))
            self.transfer_function = np.vectorize(transfer_function, otypes=[np.float64])

        def propagate(self, obj):
            return self.transfer_function(self.Weights.dot(obj) + self.bias)

    class RecurrentLayer(object):
        def __init__(self, W=None, transfer_function=poslin):
            if W is None:
                self.Weights = W
            else:
                self.Weights = None
            self.transfer_function = np.vectorize(transfer_function, otypes=[np.float64])

        def propagate(self, initial_a):
            if self.Weights is None:
                s = initial_a.shape[0]
                epsilon = 1 / (s - 1)
                epsilon -= 0.01
                epsilon *= -1
                self.Weights = np.ones((s, s))
                for i in range(s):
                    for j in range(s):
                        if i != j:
                            self.Weights[i][j] = epsilon

            a2 = self.transfer_function(self.Weights.dot(initial_a))

            while True:
                a3 = self.transfer_function(self.Weights.dot(a2))
                if not np.array_equal(a2, a3):
                    a2 = a3
                else:
                    return a3

### 3.3.2. Results

In [ ]:

banana_prototype = np.array([-1, 1, -1]).reshape((3, 1))
pineapple_prototype = np.array([-1, -1, 1]).reshape((3, 1))
prototypes = np.array([banana_prototype.T[0], pineapple_prototype.T[0]])

print("\nii. Design a Hamming network to recognize these patterns.")

test_fruit = np.array([-1, -1, -1]).reshape((3, 1))

hammingFruitClassifier = HammingNetwork(prototypes=prototypes)
print(hammingFruitClassifier.classify(obj=test_fruit))


near_pineapple = np.array([1, -1, 1]).reshape((3, 1))
near_banana = np.array([-1, 1, -1]).reshape((3, 1))
print("\t", "near_pineapple", bp_hamming.classify(near_pineapple))
print("\t", "near_banana", bp_hamming.classify(near_banana))



## 3.1.4. HopfieldNetwork

### 3.4.1. HopfieldNetwork

In [ ]:
class HopfieldNetwork(object):
    def __init__(self, weights=np.array([[0.2, 0, 0], [0, 1.2, 0], [0, 0, 0.2]]), transfer_function=satlins, bias=np.array([0.9, 0, -0.9])):
        self.weights = weights
        self.bias = bias.reshape((weights.shape[0], 1))
        self.transfer_function = np.vectorize(transfer_function, otypes=[float])
        self.activations = []

    def classify(self, a0):
        self.activations.append(a0)
        a1 = self.transfer_function(self.weights.dot(a0) + self.bias)
        self.activations.append(a1)
        if np.array_equal(a0, a1):
            return a1
        else:
            while True:
                an = self.transfer_function(self.weights.dot(a1) + self.bias)
                self.activations.append(an)
                if not np.array_equal(an, a1):
                    a1 = an
                else:
                    return an

### 3.4.2. Results

In [ ]:
W = np.array([[0.2, 0, 0], [0, 1.2, 0], [0, 0, 1.2]])
print(W)

In [ ]:
bias=np.array([-0.9, 0, 0])
print(bias)

In [ ]:
print("\niii. Design a Hopfield network to recognize thse patterns.")
bp_hopfield = HopfieldNetwork(weights = np.array([[0.2, 0, 0], [0, 1.2, 0], [0, 0, 1.2]]), bias=np.array([-0.9, 0, 0]))
print("\t", "near_pineapple", bp_hopfield.classify(near_pineapple))
print("\t", "near_banana", bp_hopfield.classify(near_banana))

In [ ]:
test_obj = np.array([-1, -1, -1]).reshape((3, 1))

test_hopfield = HopfieldNetwork()
print(test_hopfield.classify(test_obj))



---



---



# 3.2

In [ ]:
import matplotlib.pyplot as plt

# Coordinates
x = 1
y = 0.5

# Create a figure and axis
fig, ax = plt.subplots()

# Plot the vector
ax.quiver(0, 0, x, y, angles='xy', scale_units='xy', scale=1, color='b')

# Set the aspect ratio of the plot to be equal
ax.set_aspect('equal')

# Set plot limits
plt.xlim(0, 1.2)
plt.ylim(0, 0.7)

# Set labels and title
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Vector: x=1, y=0.5')

# Show the plot
plt.show()


In [ ]:

p_1 = np.array([1, 0.5]).reshape((2, 1))
p_2 = np.array([2, 1]).reshape((2, 1))


i.   Find and sketch the decision boundary for a perceptron network that will recognize these two vectors.

ii. Find weights and bias which will produce the decision boundary you found in part i, and sketch the network diagram.

In [ ]:
decision_boundary = (p_1 + p_2)/2
W = np.array([0.75, 0])
b = 0.75
print("decision_boundary", decision_boundary )
print("W", W, "b", b)


iii. Calculate the network output for the following input.  Is the network response (decision) reasonable? Explain.

In [ ]:

print("\n\tp_test = [1, 0].T")
p_test = np.array([ 1,0]).reshape((2, 1))
test_perceptron = Perceptron(W=W, b=b)
print("Classification = ", test_perceptron.classify(p_test))


 Yes this is reasonable as p_test is closer to p_1 than p_2

iv.  Design a Hamming network to recognize the two prototype vectors above.

In [ ]:

prototypes = np.array([p_1.T[0], p_2.T[0]])
test_hamming = HammingNetwork(prototypes=prototypes)
print("Classification = ", test_hamming.classify(p_test))


v. Calculate the network output for the Hamming network with the input vector given in part iii, showing all steps. Does the Hamming network produce the same deceiion as the perceptron? Explain why or why not.  Which network is better suited to this problem? Explain

*No.  The Hamming network misclassifies the test input.  This is because the Hamming network is only designed to classify problems where the input vector only has two possible values.*



---



---



# 3.3

i. The following input (initial condition) is applied to the network. Find the network response (show the network output at each iteration until the network converges)

In [ ]:
print("Consider a Hopfield network, with the follwing weight and bias.", "\n\tW = [[1, -1], [-1, 1]]  b = [0, 0].T")

weights = np.array([[1, -1], [-1, 1]])
bias = np.array([0, 0]).reshape((2, 1))

test_input = np.array([0.9, 1]).reshape((2, 1))

Network = HopfieldNetwork(weights= weights, bias = bias)
Network.classify(a0 = test_input)

print("Listing activations")
for index, activation in enumerate(Network.activations):
    print("\n", index, activation)

ii. Draw a sketch indicating what region of the input space will converge to the same final output that you found in part i. (In other words, for what other p vectors will the network converge to the same final output?) Explain how you obtained your answer

In [ ]:
x = np.linspace(-50,50)
y = x
y_edge = np.linspace(50,50)
plt.plot(x,y)
plt.fill_between(x, y, y_edge, where = y_edge > y)
plt.grid(True)
plt.show()


iii. What other prototypes will this network converge to, and what regions of the input space corresponds to each prototype (sket the regions).  Explain how you obtained your answer."


All prototypes above the line x=y because this is the decision matrix that would be generated by a weight = [[1, -1], [-1, 1]] and bias = [0, 0]"